### ISSUE TITLE
Crear prototipo inicial para la etapa de extracción de datos

### ISSUE THREAD

**Issue by liviuvj** [liviuvj/sentiment-analysis-tool#11]
Para realizar una mejor comparación de las herramientas investigadas en #10, se creará un pequeño prototipo para esta primera etapa de extracción de datos sobre las *APIs* seleccionadas en #8, empleando para ello las tecnologías escogidas más relevantes.

**Comment by alvarag** [comment]
Minor comments on the documentation
[memoriaAAG.pdf](https://github.com/liviuvj/sentiment-analysis-tool/files/10900203/memoriaAAG.pdf)

**Comment by liviuvj** [comment]
Thank you very much for the feedback. The improvements will be implemented during the issue #15.
