### ISSUE TITLE
Investigar herramienta de visualización

### ISSUE THREAD

**Issue by liviuvj** [liviuvj/sentiment-analysis-tool#50]
Una vez que se tiene todos los datos extraídos, procesados, transformados e inferidos persistidos en el sistema OLAP, se encuentran listos para su puesta en explotación. Para ello, se ha de investigar una herramienta de visualización compatible con la tecnología empleada y acorde a los requisitos de uso, que pueda explotar visualmente y de manera eficaz los datos obtenidos.

**Comment by alvarag** [comment]
Algunos comentarios sobre la documentación

[memoria-AAG.pdf](https://github.com/liviuvj/sentiment-analysis-tool/files/11685442/memoria-AAG.pdf)

**Comment by liviuvj** [comment]
Muchas gracias por los comentarios. Se procederá a implementar las correcciones provistas en #53.
