### ISSUE TITLE
Mejorar aspectos relevantes de la documentación

### ISSUE THREAD

**Issue by liviuvj** [liviuvj/sentiment-analysis-tool#78]
Se procederá a mejorar la sección *Aspectos relevantes del desarrollo del proyecto*.

**Comment by alvarag** [comment]
Algunos comentarios sobre la memoria, buen trabajo

[memoriaAAG.pdf](https://github.com/liviuvj/sentiment-analysis-platform/files/12017300/memoriaAAG.pdf)
